### ISSUE TITLE
Connect Wallet Button to show 0x Address After Login

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#1]

**Comment by novadaodev** [comment]
https://github.com/novadaox/homepage/blob/4330b9dfad08544869414703eafea7505b32da83/src/app/index/homepage/homepage.component.ts#L305-L306

**Comment by novadaodev** [comment]
@TsegaDEBEBE this does not appear to be live in any build I've tried. They should be in dev.novadao.xyz

The menu button and home page buttons that read "Connect Wallet" continue to read "Connect Wallet" despite login. They should read the address

**Comment by dave-16** [comment]
issue fixed by specifying our provider to be MetaMask !
https://github.com/NovaDAOx/homepage/blob/62b389ca6267e5dc5f74dd25e1d5dfb0b25ba40c/src/app/services/metamask.service.ts#L48-L49
