### ISSUE TITLE
staking checklist UX

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#10]
when user is not logged in, show login button (connect wallet) 
when user is logged in and moralis is loading show loading spinner or at least text 
when checklist returns empty show message "No NFTs under contract <contract var and link to etherscan>. Procure an NFT or contact support through <Discord link>."

**Comment by jb4earth** [comment]
Related to issue #12

**Comment by jb4earth** [comment]
Upon reaching the staking page the following should occur [pseudo-code]
```
if user logged in to metamask: 
    getNFTs 
    if user setApproveAll complete:
       show checklist of available NFTs to stake [go to last if condition below]
    else if setApprovaAll incomplete: 
       disable and grayout all NFTs
       show button above checklist component "Allow Nova to Stake NFTs" [runs setApproveAll] {see note 1}
else if user is not logged in: 
    show button "Log in to Metamask to Stake"
else if user logged in and setApproveAll complete: 
    show NFTs
    show Select All button [once all selected show Deselect All instead]
    show "Stake" button
```

Note 1"  {include an info button (i in circle) which shows text on hover -- "Staking NFTs requires two steps, first you must approve Nova to interact or stake your NFTs, second you'll select the NFTs you wish to stake and run the Stake command. Allowing Nove to interact with your NFTs is key is it also allows us to Unstake your NFTs and issue your rewards"}

**Comment by dave-16** [comment]
issue completed 
https://github.com/NovaDAOx/homepage/blob/2028721acc1c29b7f0d28ceb78be66f90b732bd4/src/app/index/staking/stake.component.ts#L115-L155
