### ISSUE TITLE
 ParseError: 141 No address provided or logged-in user found Error: No address provided or logged-in user found

### ISSUE THREAD

**Issue by pawanlapits** [novadaodev/homepage#12]
![image](https://user-images.githubusercontent.com/40483256/180131740-f25ea81d-686e-40be-9104-27218a253ed7.png)
This error comes when metamask not connected on staking page.

**Comment by dave-16** [comment]
yes you are right this kind of Error is occurring because their is no user connected to Metamask right? so the user have to Signin using Metamask to solve this error . am I right ? please correct me if I dont get it.

**Comment by pawanlapits** [comment]
we have to handle this case

**Comment by jb4earth** [comment]
We shouldn't call moralis until user is logged in 

Thanks for reporting this issue

**Comment by dave-16** [comment]
no address provided fixed by initiating moralis on staking page and only when user is logged in 

https://github.com/NovaDAOx/homepage/blob/4b5d3c4535c05860bbd9b8084ce8b5c3839fdbab/src/app/index/staking/stake.component.ts#L144

Thanks for reporting.
