### ISSUE TITLE
homepage update 

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#13]
link to blog at top of homepage

<iframe src="https://thesupernova.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>

**Comment by TsegaDEBEBE** [comment]
![image](https://user-images.githubusercontent.com/78467303/181707392-536c918b-e0b8-45c6-9d14-57b07f27a347.png)
![image](https://user-images.githubusercontent.com/78467303/181707548-a8001c03-d9f6-4ef1-b22c-cdc5b97a350b.png)
