### ISSUE TITLE
view staked nfts

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#16]
view all staked nfts (there's a call in the smart contract to do this use ether.js NOT moralis)

check smart contract for the following:
stakerWallet (show all nfts in wallet)

https://rinkeby.etherscan.io/viewsvg?t=1&a=0x550B38EdAe1d4868CD7e3AB4574a9E6c1fD66362

**Comment by dave-16** [comment]
https://github.com/NovaDAOx/homepage/blob/160b4b89c8dff9553f953e623702b065d258990f/src/app/services/ether.service.ts#L164-L187

we can view the staked nfts and amount
