### ISSUE TITLE
view estimated claim amount

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#17]
show staking rewards, use function below. show a small refresh button so user can check stake again without reloading the whole page

check smart contract for the following:
estimateClaim

https://rinkeby.etherscan.io/viewsvg?t=1&a=0x550B38EdAe1d4868CD7e3AB4574a9E6c1fD66362

**Comment by dave-16** [comment]
view estimated claim automatically!

https://github.com/NovaDAOx/homepage/blob/160b4b89c8dff9553f953e623702b065d258990f/src/app/services/ether.service.ts#L101

 -------------------------------------And-------------------------------------------

https://github.com/NovaDAOx/homepage/blob/160b4b89c8dff9553f953e623702b065d258990f/src/app/services/ether.service.ts#L144-L154
