### ISSUE TITLE
claim

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#19]
call `claim` on smart contract 

should be a button in the $NOVA estimate claim component such that the button only shows as active when there is $NOVA available to claim (otherwise gray and inactive)

**Comment by jb4earth** [comment]
follows issue #17

**Comment by dave-16** [comment]
https://github.com/NovaDAOx/homepage/blob/160b4b89c8dff9553f953e623702b065d258990f/src/app/index/staking/stake.component.ts#L344-L362

claim button becomes active when there is $Nova to claim
