### ISSUE TITLE
Modularize team grabbing service 

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#2]
right now we create 5 variables, from 5 functions to handle 5 team members.  There should be one component which wraps up a set up functions instead. It should live in it's own component not hoepage.component.ts

**Comment by novadaodev** [comment]
https://github.com/novadaox/homepage/blob/4330b9dfad08544869414703eafea7505b32da83/src/app/index/homepage/homepage.component.ts#L116-L117

**Comment by dave-16** [comment]
https://github.com/NovaDAOx/homepage/blob/cab11dbc01b6bb8b20389f92e2e8998f9bbdff24/src/app/index/homepage/homepage.component.html#L370
