### ISSUE TITLE
email signup move

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#22]
email signup should be on homepage not in menu ;)

**Comment by TsegaDEBEBE** [comment]
![image](https://user-images.githubusercontent.com/78467303/183150923-ddbd3b04-78b7-4e4b-8985-6c4b4de3375c.png)
![image](https://user-images.githubusercontent.com/78467303/183150959-75b2c040-4e56-41e4-bde2-9bfcdb024811.png)
