### ISSUE TITLE
transaction error or success presentation 

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#26]
when a user stakes, unstakes, claimes, or sets approveAll there should be a small popup what shows for 5 seconds after success. If the transaction failed, the popup should stay until an X button is clicked in the popup.  The popup should be green when successful and read (<transaction type> successful) or if failed it should be red and read (<transaction type> failed. <insert error message here>)

**Comment by dave-16** [comment]
transaction status is shown after transaction has failed or succeed
