### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#3]
use ether.js to
1. approveAll on staking contract (allow staking and unstaking)
2. stake selected via staking contract

**Comment by novadaodev** [comment]
should include a select all button to check off all available NFTs

**Comment by novadaodev** [comment]
https://github.com/novadaox/homepage/blob/4330b9dfad08544869414703eafea7505b32da83/src/app/index/staking

**Comment by novadaodev** [comment]
contract to interact with: https://rinkeby.etherscan.io/address/0x550B38EdAe1d4868CD7e3AB4574a9E6c1fD66362#code

**Comment by novadaodev** [comment]
outline of functions: [UML]

https://rinkeby.etherscan.io/viewsvg?t=1&a=0x550B38EdAe1d4868CD7e3AB4574a9E6c1fD66362

important functions: 
setApprovalForAll
stakeMany

**Comment by pawanlapits** [comment]
@novadaodev  I did not find ether.js

**Comment by jb4earth** [comment]
[ether js ](https://letmegooglethat.com/?q=ether+js+)

**Comment by jb4earth** [comment]
the smart contract engineer wrote some code for us 

https://gist.github.com/jb4earth/0288d6461fff5131023b82e284f704a4

https://gist.github.com/jb4earth/64a6dc382ec92ee05fbeb8cecfeddb42

please check it out and see if we can implement -- all questions should be posted here

**Comment by jb4earth** [comment]
the above code is not an exact duplicate of what we need to do - of course we will need to use the actual logged in address and the actual selected NFTs

@pawanlapits @dave-16 please do not hesitate to ask questions. if you want to speak direct to the smart contract engineer send me your discord usernames and I'll connect you

**Comment by pawanlapits** [comment]
@jb4earth  can we use web3 js
https://web3js.readthedocs.io/en/v1.7.4/

**Comment by jb4earth** [comment]
@pawanlapits absolutely -- whatever gets the job done

**Comment by jb4earth** [comment]
@pawanlapits @dave-16 

working smart contract call here: https://gist.github.com/jb4earth/01d9bb15b4369f4b1d098bf3ce75f38f

let's get this going today - we can't wait another week to get this done.

**Comment by pawanlapits** [comment]
Hi @jb4earth 

I will try to get it done by tomorrow. please let me know if you are ok with it.

**Comment by jb4earth** [comment]
branch dev2 has the most advanced version of the project 

issues -- testing on web in Rinkeby is impossible
approveAll shown even if transaction already occured on blockchain (check state of ApproveAll)
number of nfts staked not shown 
$NOVA reward not shown 
[check smart contract UML for functions to check the above values]

**Comment by jb4earth** [comment]
I am creating separate issues for all of these @pawanlapits and @dave-16 please claim issues as you are ready to writing code for them

**Comment by jb4earth** [comment]
this thread will be closed shortly in favor of issues #16 #17 #18 #19 #20

**Comment by jb4earth** [comment]
merged to dev
