### ISSUE TITLE
Unstaking

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#4]
1. view all staked nfts (there's a call in the smart contract to do this use ether.js NOT moralis)
2. show staking rewards (probably with a calculator, save this later)
3. unstake selected nfts (via ether.js)

**Comment by jb4earth** [comment]
check smart contract for the following: 
https://rinkeby.etherscan.io/viewsvg?t=1&a=0x550B38EdAe1d4868CD7e3AB4574a9E6c1fD66362

stakerWallet (show all nfts in wallet) 
estimateClaim
unstakeAll
unstakePass

**Comment by jb4earth** [comment]
This issue is being closed because it is too broad
