### ISSUE TITLE
team component broken in dev version 

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#5]
resolve before merge

**Comment by novadaodev** [comment]
main is currently working, just pull the code from there

**Comment by novadaodev** [comment]
https://github.com/novadaox/homepage/blob/4330b9dfad08544869414703eafea7505b32da83/src/app/index/homepage/components/username

**Comment by dave-16** [comment]
https://github.com/NovaDAOx/homepage/blob/cab11dbc01b6bb8b20389f92e2e8998f9bbdff24/src/app/index/homepage/components/username/username.component.html#L2-L33
