### ISSUE TITLE
Checklist styling

### ISSUE THREAD

**Issue by novadaodev** [novadaodev/homepage#8]
fix up the checklist on the staking page to match existing styles

https://github.com/novadaox/homepage/blob/4330b9dfad08544869414703eafea7505b32da83/src/app/index/staking

**Comment by TsegaDEBEBE** [comment]
![image](https://user-images.githubusercontent.com/78467303/178851114-c5cbf3ea-5074-4fbd-8852-0a50f4d6f7fe.png)
The styling is similar to the rest of the rest of the website.
